import React from 'react';
import StudentFeesHeader from './StudentFeesHeader';
// import StudentFeesTable from './StudentFeesTable';
import GlobalEmptyPage from '../common/GlobalEmptyPage';
import StudentFeesTable from './StudentFeesTable';

const rows = [
  {
    id: 1,
    name: 'Arif Hossain',
    number: '01711000001',
    email: 'arif.hossain@example.com',
    fatherName: 'Mokbul Hossain',
    fatherNumber: '01710000001',
    motherName: 'Rokeya Begum',
    motherNumber: '01710000001',
    instituteName: 'Dhaka College',
    address: 'Dhanmondi, Dhaka',
    class: 1,
    group: '',
    monthlyFees: '3000',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Nusrat Jahan',
    number: '01711000002',
    email: 'nusrat.jahan@example.com',
    fatherName: 'Jamal Uddin',
    fatherNumber: '01710000002',
    motherName: 'Nasima Akter',
    motherNumber: '01710000002',
    instituteName: 'Eden Mohila College',
    address: 'Azimpur, Dhaka',
    class: 2,
    group: '',
    monthlyFees: '3000',
    status: 'Active',
  },
  {
    id: 3,
    name: 'Rahim Uddin',
    number: '01711000003',
    email: 'rahim.uddin@example.com',
    fatherName: 'Karim Uddin',
    fatherNumber: '01710000003',
    motherName: 'Shahana Khatun',
    motherNumber: '01710000003',
    instituteName: 'Notre Dame College',
    address: 'Motijheel, Dhaka',
    class: 3,
    group: '',
    monthlyFees: '3000',
    status: 'InActive',
  },
  {
    id: 4,
    name: 'Sumaiya Akter',
    number: '01711000004',
    email: 'sumaiya.akter@example.com',
    fatherName: 'Rafiqul Islam',
    fatherNumber: '01710000004',
    motherName: 'Salma Khatun',
    motherNumber: '01710000004',
    instituteName: 'Holy Cross College',
    address: 'Tejgaon, Dhaka',
    class: 4,
    group: '',
    monthlyFees: '3000',
    status: 'Active',
  },
  {
    id: 5,
    name: 'Hasan Mahmud',
    number: '01711000005',
    email: 'hasan.mahmud@example.com',
    fatherName: 'Nazrul Islam',
    fatherNumber: '01710000005',
    motherName: 'Jahanara Begum',
    motherNumber: '01710000005',
    instituteName: 'Ideal College',
    address: 'Motijheel, Dhaka',
    class: 5,
    group: '',
    monthlyFees: '3000',
    status: 'InActive',
  },
  {
    id: 6,
    name: 'Mithila Haque',
    number: '01711000006',
    email: 'mithila.haque@example.com',
    fatherName: 'Firoz Haque',
    fatherNumber: '01710000006',
    motherName: 'Shamima Haque',
    motherNumber: '01710000006',
    instituteName: 'Viqarunnisa Noon College',
    address: 'Baily Road, Dhaka',
    class: 6,
    group: '',
    monthlyFees: '3000',
    status: 'InActive',
  },
  {
    id: 7,
    name: 'Imran Hossain',
    number: '01711000007',
    email: 'imran.hossain@example.com',
    fatherName: 'Helal Uddin',
    fatherNumber: '01710000007',
    motherName: 'Rabeya Begum',
    motherNumber: '01710000007',
    instituteName: 'City College',
    address: 'Dhanmondi, Dhaka',
    class: 7,
    group: '',
    monthlyFees: '3000',
    status: 'Active',
  },
  {
    id: 8,
    name: 'Tanisha Rahman',
    number: '01711000008',
    email: 'tanisha.rahman@example.com',
    fatherName: 'Sazzad Rahman',
    fatherNumber: '01710000008',
    motherName: 'Nargis Sultana',
    motherNumber: '01710000008',
    instituteName: 'Eden Mohila College',
    address: 'Azimpur, Dhaka',
    class: 8,
    group: '',
    monthlyFees: '3000',
    status: 'InActive',
  },
  {
    id: 9,
    name: 'Jamal Hossain',
    number: '01711000009',
    email: 'jamal.hossain@example.com',
    fatherName: 'Shamsul Haque',
    fatherNumber: '01710000009',
    motherName: 'Amena Begum',
    motherNumber: '01710000009',
    instituteName: 'Notre Dame College',
    address: 'Motijheel, Dhaka',
    class: 9,
    group: 'SCIENCE',
    monthlyFees: '3000',
    status: 'InActive',
  },
  {
    id: 10,
    name: 'Farzana Akter',
    number: '01711000010',
    email: 'farzana.akter@example.com',
    fatherName: 'Hasan Ali',
    fatherNumber: '01710000010',
    motherName: 'Rehana Akter',
    motherNumber: '01710000010',
    instituteName: 'Holy Cross College',
    address: 'Tejgaon, Dhaka',
    class: 10,
    group: 'COMMERCE',
    monthlyFees: '3000',
    status: 'Active'
  },
  {
    id: 11,
    name: 'Shuvo Roy',
    number: '01711000011',
    email: 'shuvo.roy@example.com',
    fatherName: 'Subhash Roy',
    fatherNumber: '01710000011',
    motherName: 'Moni Roy',
    motherNumber: '01710000011',
    instituteName: 'Dhaka College',
    address: 'New Market, Dhaka',
    class: 11,
    group: 'ARTS',
    monthlyFees: '3000',
    status: 'InActive'
  },
  {
    id: 12,
    name: 'Tania Islam',
    number: '01711000012',
    email: 'tania.islam@example.com',
    fatherName: 'Jahangir Alam',
    fatherNumber: '01710000012',
    motherName: 'Lamia Begum',
    motherNumber: '01710000012',
    instituteName: 'Viqarunnisa Noon College',
    address: 'Baily Road, Dhaka',
    class: 12,
    group: 'SCIENCE',
    monthlyFees: '3000',
    status: 'InActive'
  },
  {
    id: 13,
    name: 'Omar Faruk',
    number: '01711000013',
    email: 'omar.faruk@example.com',
    fatherName: 'Anwar Hossain',
    fatherNumber: '01710000013',
    motherName: 'Sharmin Akter',
    motherNumber: '01710000013',
    instituteName: 'Ideal College',
    address: 'Motijheel, Dhaka',
    class: 1,
    group: '',
    monthlyFees: '3000',
    status: 'Active'
  },
  {
    id: 14,
    name: 'Rima Khatun',
    number: '01711000014',
    email: 'rima.khatun@example.com',
    fatherName: 'Golam Mostafa',
    fatherNumber: '01710000014',
    motherName: 'Fahima Begum',
    motherNumber: '01710000014',
    instituteName: 'Eden Mohila College',
    address: 'Azimpur, Dhaka',
    class: 2,
    group: '',
    monthlyFees: '3000',
    status: 'Active'
  },
  {
    id: 15,
    name: 'Nayeem Islam',
    number: '01711000015',
    email: 'nayeem.islam@example.com',
    fatherName: 'Moinul Islam',
    fatherNumber: '01710000015',
    motherName: 'Nasima Begum',
    motherNumber: '01710000015',
    instituteName: 'Notre Dame College',
    address: 'Motijheel, Dhaka',
    class: 3,
    group: '',
    monthlyFees: '3000',
    status: 'InActive'
  },
  {
    id: 16,
    name: 'Anika Sultana',
    number: '01711000016',
    email: 'anika.sultana@example.com',
    fatherName: 'Moshiur Rahman',
    fatherNumber: '01710000016',
    motherName: 'Khadija Sultana',
    motherNumber: '01710000016',
    instituteName: 'Holy Cross College',
    address: 'Tejgaon, Dhaka',
    class: 4,
    group: '',
    monthlyFees: '3000',
    status: 'Active'
  },
  {
    id: 17,
    name: 'Sajid Khan',
    number: '01711000017',
    email: 'sajid.khan@example.com',
    fatherName: 'Jahangir Kabir',
    fatherNumber: '01710000017',
    motherName: 'Shirin Akter',
    motherNumber: '01710000017',
    instituteName: 'City College',
    address: 'Dhanmondi , Dhaka',
    class: 5,
    group: '',
    monthlyFees: '3000',
    status: 'Active',
    },
    {
id: 18,
name: 'Rafiq Ahmed',
number: '01711000018',
email: 'rafiq.ahmed@example.com',
fatherName: 'Zakir Hossain',
fatherNumber: '01710000018',
motherName: 'Firoza Begum',
motherNumber: '01710000018',
instituteName: 'Ideal College',
address: 'Motijheel, Dhaka',
class: 6,
group: '',
monthlyFees: '3000',
status: 'Active'
},
{
id: 19,
name: 'Priya Das',
number: '01711000019',
email: 'priya.das@example.com',
fatherName: 'Biplob Das',
fatherNumber: '01710000019',
motherName: 'Nila Das',
motherNumber: '01710000019',
instituteName: 'Eden Mohila College',
address: 'Azimpur, Dhaka',
class: 7,
group: '',
monthlyFees: '3000',
status: 'InActive'
},
{
id: 20,
name: 'Zahidul Islam',
number: '01711000020',
email: 'zahidul.islam@example.com',
fatherName: 'Abdur Rahim',
fatherNumber: '01710000020',
motherName: 'Momena Begum',
motherNumber: '01710000020',
instituteName: 'Notre Dame College',
address: 'Motijheel, Dhaka',
class: 8,
group: '',
monthlyFees: '3000',
status: 'Active'
},
{
id: 21,
name: 'Laboni Akter',
number: '01711000021',
email: 'laboni.akter@example.com',
fatherName: 'Saiful Islam',
fatherNumber: '01710000021',
motherName: 'Halima Khatun',
motherNumber: '01710000021',
instituteName: 'Holy Cross College',
address: 'Tejgaon, Dhaka',
class: 9,
group: 'COMMERCE',
monthlyFees: '3000',
status: 'InActive'
},
{
id: 22,
name: 'Arman Ali',
number: '01711000022',
email: 'arman.ali@example.com',
fatherName: 'Nazmul Huda',
fatherNumber: '01710000022',
motherName: 'Selina Akter',
motherNumber: '01710000022',
instituteName: 'Dhaka College',
address: 'Dhanmondi, Dhaka',
class: 10,
group: 'ARTS',
monthlyFees: '3000',
status: 'Active'
},
{
id: 23,
name: 'Shamima Nasrin',
number: '01711000023',
email: 'shamima.nasrin@example.com',
fatherName: 'Shah Alam',
fatherNumber: '01710000023',
motherName: 'Razia Sultana',
motherNumber: '01710000023',
instituteName: 'Eden Mohila College',
address: 'Azimpur, Dhaka',
class: 11,
group: 'SCIENCE',
monthlyFees: '3000',
status: 'InActive'

},
{
id: 24,
name: 'Fahim Hossain',
number: '01711000024',
email: 'fahim.hossain@example.com',
fatherName: 'Kamrul Hossain',
fatherNumber: '01710000024',
motherName: 'Fatema Begum',
motherNumber: '01710000024',
instituteName: 'City College',
address: 'Dhanmondi, Dhaka',
class: 12,
group: 'COMMERCE',
monthlyFees: '3000',
status: 'Active'
},
{
id: 25,
name: 'Kawsar Ali',
number: '01711000025',
email: 'kawsar.ali@example.com',
fatherName: 'Motahar Hossain',
fatherNumber: '01710000025',
motherName: 'Hamida Begum',
motherNumber: '01710000025',
instituteName: 'Dhaka City College',
address: 'Dhanmondi, Dhaka',
class: 1,
group: '',
monthlyFees: '3000',
status: 'InActive'
}
];

const StudentFees = () => {
    return (
         <div style={{width:'100%', height:'100%', backgroundColor:'#ffffff', borderRadius:'6px', padding:'20px', display:'flex', flexDirection:'column', gap:'32px'}}>
            <StudentFeesHeader/>
            {/* { (Array.isArray(rows) && rows.length > 0 ) ? ( */}
                <StudentFeesTable />
                {/* ) : (
                <GlobalEmptyPage message="No Student found" showAddButton={true}/>
            )} */}
        </div>
    );
};

export default StudentFees;